//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControllerError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControllerError() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.ControllerError", typeof(ControllerError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured, sorry for that!.
        /// </summary>
        public static string ajaxError {
            get {
                return ResourceManager.GetString("ajaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while accepting or disaccepting the answer....
        /// </summary>
        public static string ajaxErrorAnswerAcception {
            get {
                return ResourceManager.GetString("ajaxErrorAnswerAcception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting answer... Sorry!.
        /// </summary>
        public static string ajaxErrorAnswerDelete {
            get {
                return ResourceManager.GetString("ajaxErrorAnswerDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while editing answer... Sorry!.
        /// </summary>
        public static string ajaxErrorAnswerEdit {
            get {
                return ResourceManager.GetString("ajaxErrorAnswerEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while inserting answer... Sorry!.
        /// </summary>
        public static string ajaxErrorAnswerInsert {
            get {
                return ResourceManager.GetString("ajaxErrorAnswerInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not admin of this company... .
        /// </summary>
        public static string ajaxErrorCertificateCoAdmin {
            get {
                return ResourceManager.GetString("ajaxErrorCertificateCoAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting certificate... Sorry!.
        /// </summary>
        public static string ajaxErrorCertificateDelete {
            get {
                return ResourceManager.GetString("ajaxErrorCertificateDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while editing Certificate... Sorry!.
        /// </summary>
        public static string ajaxErrorCertificateEdit {
            get {
                return ResourceManager.GetString("ajaxErrorCertificateEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while inserting comment... Sorry!.
        /// </summary>
        public static string ajaxErrorComment {
            get {
                return ResourceManager.GetString("ajaxErrorComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating Education... Sorry!.
        /// </summary>
        public static string ajaxErrorEducationCreate {
            get {
                return ResourceManager.GetString("ajaxErrorEducationCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting Education... Sorry!.
        /// </summary>
        public static string ajaxErrorEducationDelete {
            get {
                return ResourceManager.GetString("ajaxErrorEducationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while editing Education... Sorry!.
        /// </summary>
        public static string ajaxErrorEducationEdit {
            get {
                return ResourceManager.GetString("ajaxErrorEducationEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not admin of this item..
        /// </summary>
        public static string ajaxErrorEducationUser {
            get {
                return ResourceManager.GetString("ajaxErrorEducationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating event... Sorry!.
        /// </summary>
        public static string ajaxErrorEventCreate {
            get {
                return ResourceManager.GetString("ajaxErrorEventCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting event... Sorry!.
        /// </summary>
        public static string ajaxErrorEventDelete {
            get {
                return ResourceManager.GetString("ajaxErrorEventDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while editing event... Sorry!.
        /// </summary>
        public static string ajaxErrorEventEdit {
            get {
                return ResourceManager.GetString("ajaxErrorEventEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not admin of this item..
        /// </summary>
        public static string ajaxErrorEventUser {
            get {
                return ResourceManager.GetString("ajaxErrorEventUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while following....
        /// </summary>
        public static string ajaxErrorFollowing {
            get {
                return ResourceManager.GetString("ajaxErrorFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! an error occured,Try again Later Please....
        /// </summary>
        public static string ajaxErrorFriendRequest {
            get {
                return ResourceManager.GetString("ajaxErrorFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! An error occured while sending friend request....
        /// </summary>
        public static string ajaxErrorFriendRequestAdd {
            get {
                return ResourceManager.GetString("ajaxErrorFriendRequestAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! An error occured while dening friend request....
        /// </summary>
        public static string ajaxErrorFriendRequestDeny {
            get {
                return ResourceManager.GetString("ajaxErrorFriendRequestDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! An error occured while ignoring user....
        /// </summary>
        public static string ajaxErrorFriendRequestIgnore {
            get {
                return ResourceManager.GetString("ajaxErrorFriendRequestIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your are deleting all admins! the group should have at lease one admin.
        /// </summary>
        public static string ajaxErrorGroupAdminDelete {
            get {
                return ResourceManager.GetString("ajaxErrorGroupAdminDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while inserting like... Sorry!.
        /// </summary>
        public static string ajaxErrorLike {
            get {
                return ResourceManager.GetString("ajaxErrorLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your values are not valid....
        /// </summary>
        public static string ajaxErrorModelState {
            get {
                return ResourceManager.GetString("ajaxErrorModelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating patent... Sorry!.
        /// </summary>
        public static string ajaxErrorPatentCreate {
            get {
                return ResourceManager.GetString("ajaxErrorPatentCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting patent... Sorry!.
        /// </summary>
        public static string ajaxErrorPatentDelete {
            get {
                return ResourceManager.GetString("ajaxErrorPatentDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while edit patent... Sorry!.
        /// </summary>
        public static string ajaxErrorPatentEdit {
            get {
                return ResourceManager.GetString("ajaxErrorPatentEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not admin of this item..
        /// </summary>
        public static string ajaxErrorPatentUser {
            get {
                return ResourceManager.GetString("ajaxErrorPatentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting post... Sorry!.
        /// </summary>
        public static string ajaxErrorPostDelete {
            get {
                return ResourceManager.GetString("ajaxErrorPostDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while editing post... Sorry!.
        /// </summary>
        public static string ajaxErrorPostEdit {
            get {
                return ResourceManager.GetString("ajaxErrorPostEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while inserting post... Sorry!.
        /// </summary>
        public static string ajaxErrorPostInsert {
            get {
                return ResourceManager.GetString("ajaxErrorPostInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not admin of this company....
        /// </summary>
        public static string ajaxErrorProductAdmin {
            get {
                return ResourceManager.GetString("ajaxErrorProductAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting product... Sorry!.
        /// </summary>
        public static string ajaxErrorProductDelete {
            get {
                return ResourceManager.GetString("ajaxErrorProductDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting profile pic... Sorry!.
        /// </summary>
        public static string ajaxErrorProfilePicDelete {
            get {
                return ResourceManager.GetString("ajaxErrorProfilePicDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while uploading profile pic... Sorry!.
        /// </summary>
        public static string ajaxErrorProfilePicUpload {
            get {
                return ResourceManager.GetString("ajaxErrorProfilePicUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not admin of this question....
        /// </summary>
        public static string ajaxErrorQuestionAdmin {
            get {
                return ResourceManager.GetString("ajaxErrorQuestionAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting question... Sorry!.
        /// </summary>
        public static string ajaxErrorQuestionDelete {
            get {
                return ResourceManager.GetString("ajaxErrorQuestionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webinar moderator should be choosed..
        /// </summary>
        public static string ajaxErrorSemAdmin {
            get {
                return ResourceManager.GetString("ajaxErrorSemAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! An error occured while sharing....
        /// </summary>
        public static string ajaxErrorShare {
            get {
                return ResourceManager.GetString("ajaxErrorShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your word is present in the words list, please try again and choose from list..
        /// </summary>
        public static string ajaxErrorWordDuplicate {
            get {
                return ResourceManager.GetString("ajaxErrorWordDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The english word is duplicate, try to edit word or choose from list apeared while typing..
        /// </summary>
        public static string ajaxErrorWordDuplicateEn {
            get {
                return ResourceManager.GetString("ajaxErrorWordDuplicateEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The not english word is duplicate, try to edit word or choose from list apeared while typing..
        /// </summary>
        public static string ajaxErrorWordDuplicateFa {
            get {
                return ResourceManager.GetString("ajaxErrorWordDuplicateFa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size is more than allowed....
        /// </summary>
        public static string ajaxFileSize {
            get {
                return ResourceManager.GetString("ajaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not supported.
        /// </summary>
        public static string ajaxFileType {
            get {
                return ResourceManager.GetString("ajaxFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Upload error....
        /// </summary>
        public static string ajaxFileUploadError {
            get {
                return ResourceManager.GetString("ajaxFileUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while cropping image....
        /// </summary>
        public static string ajaxImageCropError {
            get {
                return ResourceManager.GetString("ajaxImageCropError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while resizing image....
        /// </summary>
        public static string ajaxImageResizeError {
            get {
                return ResourceManager.GetString("ajaxImageResizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s) must be uploaded.
        /// </summary>
        public static string bookMustUpload {
            get {
                return ResourceManager.GetString("bookMustUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A document file must be uploaded at least..
        /// </summary>
        public static string bookMustUploadOneDoc {
            get {
                return ResourceManager.GetString("bookMustUploadOneDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A document file must be uploaded, you can upload an image too..
        /// </summary>
        public static string bookMustUploadOneDocAndImage {
            get {
                return ResourceManager.GetString("bookMustUploadOneDocAndImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email you entered not found..
        /// </summary>
        public static string emailWasNotFound {
            get {
                return ResourceManager.GetString("emailWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request, if this persists, Contact the administrator....
        /// </summary>
        public static string errorGlobal {
            get {
                return ResourceManager.GetString("errorGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, The resource you want not found....
        /// </summary>
        public static string errorNotFound {
            get {
                return ResourceManager.GetString("errorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So many files uploaded.
        /// </summary>
        public static string fileCountExceeded {
            get {
                return ResourceManager.GetString("fileCountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A username for that e-mail address already exists. Please enter a different e-mail address..
        /// </summary>
        public static string MembershipError_DuplicateEmail {
            get {
                return ResourceManager.GetString("MembershipError_DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists. Please enter a different user name..
        /// </summary>
        public static string MembershipError_DuplicateUserName {
            get {
                return ResourceManager.GetString("MembershipError_DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string MembershipError_GeneralError {
            get {
                return ResourceManager.GetString("MembershipError_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval answer provided is invalid. Please check the value and try again..
        /// </summary>
        public static string MembershipError_InvalidAnswer {
            get {
                return ResourceManager.GetString("MembershipError_InvalidAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail address provided is invalid. Please check the value and try again..
        /// </summary>
        public static string MembershipError_InvalidEmail {
            get {
                return ResourceManager.GetString("MembershipError_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password provided is invalid. Please enter a valid password value..
        /// </summary>
        public static string MembershipError_InvalidPassword {
            get {
                return ResourceManager.GetString("MembershipError_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval question provided is invalid. Please check the value and try again..
        /// </summary>
        public static string MembershipError_InvalidQuestion {
            get {
                return ResourceManager.GetString("MembershipError_InvalidQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name provided is invalid. Please check the value and try again..
        /// </summary>
        public static string MembershipError_InvalidUserName {
            get {
                return ResourceManager.GetString("MembershipError_InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string MembershipError_ProviderError {
            get {
                return ResourceManager.GetString("MembershipError_ProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string MembershipError_UserRejected {
            get {
                return ResourceManager.GetString("MembershipError_UserRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! an error occurred while processing your request. check your data and retry..
        /// </summary>
        public static string modelstateError {
            get {
                return ResourceManager.GetString("modelstateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is wrong!.
        /// </summary>
        public static string nameOrPassIncorrect {
            get {
                return ResourceManager.GetString("nameOrPassIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string notFound {
            get {
                return ResourceManager.GetString("notFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Your web browser is too old!
        ///please click on links below to download the latest browser..
        /// </summary>
        public static string OldBrowserHelp {
            get {
                return ResourceManager.GetString("OldBrowserHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect or the new password is invalid..
        /// </summary>
        public static string passWordChangeError {
            get {
                return ResourceManager.GetString("passWordChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan is Wrong....
        /// </summary>
        public static string planQuery {
            get {
                return ResourceManager.GetString("planQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reqistration successfull, but an error occurred while sending email, please click on link below to retry..
        /// </summary>
        public static string registerActivationEmailError {
            get {
                return ResourceManager.GetString("registerActivationEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while resending of confirmation email..
        /// </summary>
        public static string resendConfirmationEmailError {
            get {
                return ResourceManager.GetString("resendConfirmationEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word you are going to add to this dictionary, is present as following, you can edit this word description instead..
        /// </summary>
        public static string wordIsPresentInDic {
            get {
                return ResourceManager.GetString("wordIsPresentInDic", resourceCulture);
            }
        }
    }
}
