//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.ModelValidation", typeof(ModelValidation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent category is choosed, No need for childs....
        /// </summary>
        public static string categoryParentIsChoosed {
            get {
                return ResourceManager.GetString("categoryParentIsChoosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be between {2} and {1} characters.
        /// </summary>
        public static string CharactersBetween {
            get {
                return ResourceManager.GetString("CharactersBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code.
        /// </summary>
        public static string countryCode {
            get {
                return ResourceManager.GetString("countryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be date value.
        /// </summary>
        public static string datetime {
            get {
                return ResourceManager.GetString("datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digits count is not right..
        /// </summary>
        public static string digitCount {
            get {
                return ResourceManager.GetString("digitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address must be like example@gmail.com.
        /// </summary>
        public static string emailField {
            get {
                return ResourceManager.GetString("emailField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only documents are supported.
        /// </summary>
        public static string fileTypeDoc {
            get {
                return ResourceManager.GetString("fileTypeDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Images are supported.
        /// </summary>
        public static string fileTypeIMG {
            get {
                return ResourceManager.GetString("fileTypeIMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type not supported.
        /// </summary>
        public static string fileTypeLimit {
            get {
                return ResourceManager.GetString("fileTypeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Video files are supported.
        /// </summary>
        public static string fileTypeVideo {
            get {
                return ResourceManager.GetString("fileTypeVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float value is incorrect..
        /// </summary>
        public static string invalidFloat {
            get {
                return ResourceManager.GetString("invalidFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than {1} characters.
        /// </summary>
        public static string maxCharacters {
            get {
                return ResourceManager.GetString("maxCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry... more files are not supported..
        /// </summary>
        public static string maxUploadFileCount {
            get {
                return ResourceManager.GetString("maxUploadFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max upload file size is 1MB.
        /// </summary>
        public static string maxUploadFileLimit {
            get {
                return ResourceManager.GetString("maxUploadFileLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max upload file size is 30MB.
        /// </summary>
        public static string maxUploadFileLimitBook {
            get {
                return ResourceManager.GetString("maxUploadFileLimitBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melli Code is not acceptable..
        /// </summary>
        public static string melliCode {
            get {
                return ResourceManager.GetString("melliCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Must be at leaste {2} characters.
        /// </summary>
        public static string minCharacters {
            get {
                return ResourceManager.GetString("minCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number.
        /// </summary>
        public static string mobileNo {
            get {
                return ResourceManager.GetString("mobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your entered data is not valid, Try again please and if the problem persists, Contact administrator... Sorry!.
        /// </summary>
        public static string modelNotValid {
            get {
                return ResourceManager.GetString("modelNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry must be Inetger.
        /// </summary>
        public static string mustInt {
            get {
                return ResourceManager.GetString("mustInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry must be number..
        /// </summary>
        public static string mustNumber {
            get {
                return ResourceManager.GetString("mustNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be between {2} and {1} characters.
        /// </summary>
        public static string numberBeetween {
            get {
                return ResourceManager.GetString("numberBeetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string passMissMatch {
            get {
                return ResourceManager.GetString("passMissMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay amount must be less than {1}..
        /// </summary>
        public static string payAmount {
            get {
                return ResourceManager.GetString("payAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay code is not valid..
        /// </summary>
        public static string payCode {
            get {
                return ResourceManager.GetString("payCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Date Must Be Later....
        /// </summary>
        public static string secondDateMustbeLater {
            get {
                return ResourceManager.GetString("secondDateMustbeLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than {1}.
        /// </summary>
        public static string semDuration {
            get {
                return ResourceManager.GetString("semDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than {1}.
        /// </summary>
        public static string semMaxAudience {
            get {
                return ResourceManager.GetString("semMaxAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of range.
        /// </summary>
        public static string semPrice {
            get {
                return ResourceManager.GetString("semPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code.
        /// </summary>
        public static string stateCode {
            get {
                return ResourceManager.GetString("stateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered number is too long!.
        /// </summary>
        public static string tooLongFloat {
            get {
                return ResourceManager.GetString("tooLongFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address must be contain http://....
        /// </summary>
        public static string urlField {
            get {
                return ResourceManager.GetString("urlField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White space is not allowed..
        /// </summary>
        public static string whitSpaceNotAllowed {
            get {
                return ResourceManager.GetString("whitSpaceNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum months allowed is {2}.
        /// </summary>
        public static string wuaranteeMonths {
            get {
                return ResourceManager.GetString("wuaranteeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can olny choose 5 professions.
        /// </summary>
        public static string YouCanChooseMax5Professions {
            get {
                return ResourceManager.GetString("YouCanChooseMax5Professions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can olny choose 7 categories.
        /// </summary>
        public static string YouCanChooseMaxCategories {
            get {
                return ResourceManager.GetString("YouCanChooseMaxCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose at leaste one item.
        /// </summary>
        public static string YouMustChoose {
            get {
                return ResourceManager.GetString("YouMustChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Field Is Required.
        /// </summary>
        public static string YouMustSpecify {
            get {
                return ResourceManager.GetString("YouMustSpecify", resourceCulture);
            }
        }
    }
}
