//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelDisplayName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelDisplayName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.ModelDisplayName", typeof(ModelDisplayName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Company (Not English).
        /// </summary>
        public static string aboutCo {
            get {
                return ResourceManager.GetString("aboutCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Company (English).
        /// </summary>
        public static string aboutCoEN {
            get {
                return ResourceManager.GetString("aboutCoEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter some information about firm you want to register....
        /// </summary>
        public static string aboutPlanReq {
            get {
                return ResourceManager.GetString("aboutPlanReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description  (Not English).
        /// </summary>
        public static string aboutProduct {
            get {
                return ResourceManager.GetString("aboutProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (English).
        /// </summary>
        public static string aboutProductEN {
            get {
                return ResourceManager.GetString("aboutProductEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description  (Not English).
        /// </summary>
        public static string aboutService {
            get {
                return ResourceManager.GetString("aboutService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description  (English).
        /// </summary>
        public static string aboutServiceEN {
            get {
                return ResourceManager.GetString("aboutServiceEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description  (Not English).
        /// </summary>
        public static string aboutStore {
            get {
                return ResourceManager.GetString("aboutStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description  (English).
        /// </summary>
        public static string aboutStoreEN {
            get {
                return ResourceManager.GetString("aboutStoreEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About you (Not English).
        /// </summary>
        public static string aboutUser {
            get {
                return ResourceManager.GetString("aboutUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About you (English).
        /// </summary>
        public static string aboutUserEN {
            get {
                return ResourceManager.GetString("aboutUserEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abuse description.
        /// </summary>
        public static string abuseDesc {
            get {
                return ResourceManager.GetString("abuseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project offer acception.
        /// </summary>
        public static string acceptedProjectOffer {
            get {
                return ResourceManager.GetString("acceptedProjectOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (Not English).
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (English).
        /// </summary>
        public static string addressEN {
            get {
                return ResourceManager.GetString("addressEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After sale Services (Months).
        /// </summary>
        public static string afterSale {
            get {
                return ResourceManager.GetString("afterSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string age {
            get {
                return ResourceManager.GetString("age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string answerBody {
            get {
                return ResourceManager.GetString("answerBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer by.
        /// </summary>
        public static string answerer {
            get {
                return ResourceManager.GetString("answerer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string approve {
            get {
                return ResourceManager.GetString("approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear color.
        /// </summary>
        public static string badgeColor {
            get {
                return ResourceManager.GetString("badgeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string badgeDesc {
            get {
                return ResourceManager.GetString("badgeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear description in english.
        /// </summary>
        public static string badgeDescEN {
            get {
                return ResourceManager.GetString("badgeDescEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear name.
        /// </summary>
        public static string badgeName {
            get {
                return ResourceManager.GetString("badgeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear name in english.
        /// </summary>
        public static string badgeNameEN {
            get {
                return ResourceManager.GetString("badgeNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string birthday {
            get {
                return ResourceManager.GetString("birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract.
        /// </summary>
        public static string bookAbstract {
            get {
                return ResourceManager.GetString("bookAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string bookPrint {
            get {
                return ResourceManager.GetString("bookPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string bookTitle {
            get {
                return ResourceManager.GetString("bookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translator.
        /// </summary>
        public static string bookTranslator {
            get {
                return ResourceManager.GetString("bookTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writer.
        /// </summary>
        public static string bookWriter {
            get {
                return ResourceManager.GetString("bookWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand name (Not English).
        /// </summary>
        public static string brandName {
            get {
                return ResourceManager.GetString("brandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand name (English).
        /// </summary>
        public static string brandNameEN {
            get {
                return ResourceManager.GetString("brandNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        public static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category (Not English).
        /// </summary>
        public static string catName {
            get {
                return ResourceManager.GetString("catName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category (English).
        /// </summary>
        public static string catNameEN {
            get {
                return ResourceManager.GetString("catNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate name (Not English).
        /// </summary>
        public static string certificate {
            get {
                return ResourceManager.GetString("certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate name (English).
        /// </summary>
        public static string certificateEN {
            get {
                return ResourceManager.GetString("certificateEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence No..
        /// </summary>
        public static string certificateLicence {
            get {
                return ResourceManager.GetString("certificateLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate or authority website address.
        /// </summary>
        public static string certificateURL {
            get {
                return ResourceManager.GetString("certificateURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter authority (Not English).
        /// </summary>
        public static string certificator {
            get {
                return ResourceManager.GetString("certificator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter authority (English).
        /// </summary>
        public static string certificatorEN {
            get {
                return ResourceManager.GetString("certificatorEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Size.
        /// </summary>
        public static string companySize {
            get {
                return ResourceManager.GetString("companySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name (Not English).
        /// </summary>
        public static string coName {
            get {
                return ResourceManager.GetString("coName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name (English).
        /// </summary>
        public static string coNameEN {
            get {
                return ResourceManager.GetString("coNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country code.
        /// </summary>
        public static string countryCode {
            get {
                return ResourceManager.GetString("countryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover photo.
        /// </summary>
        public static string cover {
            get {
                return ResourceManager.GetString("cover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string createDate {
            get {
                return ResourceManager.GetString("createDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string creationDate {
            get {
                return ResourceManager.GetString("creationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string cultureAbout {
            get {
                return ResourceManager.GetString("cultureAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string cultureAddress {
            get {
                return ResourceManager.GetString("cultureAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string cultureBrandName {
            get {
                return ResourceManager.GetString("cultureBrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate title.
        /// </summary>
        public static string cultureCertificateName {
            get {
                return ResourceManager.GetString("cultureCertificateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate authority.
        /// </summary>
        public static string cultureCertificator {
            get {
                return ResourceManager.GetString("cultureCertificator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string cultureCoName {
            get {
                return ResourceManager.GetString("cultureCoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string cultureDescription {
            get {
                return ResourceManager.GetString("cultureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event title.
        /// </summary>
        public static string cultureEventSubj {
            get {
                return ResourceManager.GetString("cultureEventSubj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field of study.
        /// </summary>
        public static string culturefieldOfStudy {
            get {
                return ResourceManager.GetString("culturefieldOfStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string cultureFullName {
            get {
                return ResourceManager.GetString("cultureFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patent title.
        /// </summary>
        public static string culturePatentTitle {
            get {
                return ResourceManager.GetString("culturePatentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        public static string cultureProductName {
            get {
                return ResourceManager.GetString("cultureProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession Description.
        /// </summary>
        public static string cultureProfessionDesc {
            get {
                return ResourceManager.GetString("cultureProfessionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession title.
        /// </summary>
        public static string cultureProfessionName {
            get {
                return ResourceManager.GetString("cultureProfessionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        public static string cultureSchool {
            get {
                return ResourceManager.GetString("cultureSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name.
        /// </summary>
        public static string cultureServiceName {
            get {
                return ResourceManager.GetString("cultureServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string cultureStateName {
            get {
                return ResourceManager.GetString("cultureStateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store name.
        /// </summary>
        public static string cultureStoreName {
            get {
                return ResourceManager.GetString("cultureStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture title.
        /// </summary>
        public static string cultureTitle {
            get {
                return ResourceManager.GetString("cultureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string currentPass {
            get {
                return ResourceManager.GetString("currentPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description(Not English).
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description(English).
        /// </summary>
        public static string descriptionEN {
            get {
                return ResourceManager.GetString("descriptionEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string dicDesc {
            get {
                return ResourceManager.GetString("dicDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary title.
        /// </summary>
        public static string dicName {
            get {
                return ResourceManager.GetString("dicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economic code.
        /// </summary>
        public static string ecoCode {
            get {
                return ResourceManager.GetString("ecoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education degree.
        /// </summary>
        public static string educationDegree {
            get {
                return ResourceManager.GetString("educationDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attend date.
        /// </summary>
        public static string eduStartDate {
            get {
                return ResourceManager.GetString("eduStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until date.
        /// </summary>
        public static string eduUntilDate {
            get {
                return ResourceManager.GetString("eduUntilDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Initiation date.
        /// </summary>
        public static string eventDate {
            get {
                return ResourceManager.GetString("eventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Subject (Not English).
        /// </summary>
        public static string eventSubj {
            get {
                return ResourceManager.GetString("eventSubj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Subject (English).
        /// </summary>
        public static string eventSubjEN {
            get {
                return ResourceManager.GetString("eventSubjEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event until Date.
        /// </summary>
        public static string eventUntilDate {
            get {
                return ResourceManager.GetString("eventUntilDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience description (Not English).
        /// </summary>
        public static string experienceDescription {
            get {
                return ResourceManager.GetString("experienceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience description (English).
        /// </summary>
        public static string experienceDescriptionEN {
            get {
                return ResourceManager.GetString("experienceDescriptionEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience State.
        /// </summary>
        public static string experienceState {
            get {
                return ResourceManager.GetString("experienceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience title (Not English).
        /// </summary>
        public static string experienceTitle {
            get {
                return ResourceManager.GetString("experienceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience title (English).
        /// </summary>
        public static string experienceTitleEN {
            get {
                return ResourceManager.GetString("experienceTitleEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string expStartDate {
            get {
                return ResourceManager.GetString("expStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until date.
        /// </summary>
        public static string expUntilDate {
            get {
                return ResourceManager.GetString("expUntilDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax No..
        /// </summary>
        public static string faxNo {
            get {
                return ResourceManager.GetString("faxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field of study (Not English).
        /// </summary>
        public static string fieldOfStudy {
            get {
                return ResourceManager.GetString("fieldOfStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field of study (English).
        /// </summary>
        public static string fieldOfStudyEN {
            get {
                return ResourceManager.GetString("fieldOfStudyEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name (Not English).
        /// </summary>
        public static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name (English).
        /// </summary>
        public static string firstNameEN {
            get {
                return ResourceManager.GetString("firstNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group description.
        /// </summary>
        public static string groupDesc {
            get {
                return ResourceManager.GetString("groupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public group.
        /// </summary>
        public static string groupIsPublic {
            get {
                return ResourceManager.GetString("groupIsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group title.
        /// </summary>
        public static string groupName {
            get {
                return ResourceManager.GetString("groupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarantee (Months).
        /// </summary>
        public static string guarantee {
            get {
                return ResourceManager.GetString("guarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height (cm).
        /// </summary>
        public static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventor(s).
        /// </summary>
        public static string inventors {
            get {
                return ResourceManager.GetString("inventors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran code.
        /// </summary>
        public static string iranCode {
            get {
                return ResourceManager.GetString("iranCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer is useful.
        /// </summary>
        public static string isUseful {
            get {
                return ResourceManager.GetString("isUseful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string jobCompany {
            get {
                return ResourceManager.GetString("jobCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Description.
        /// </summary>
        public static string jobDescription {
            get {
                return ResourceManager.GetString("jobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Offers.
        /// </summary>
        public static string JobOffers {
            get {
                return ResourceManager.GetString("JobOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professions Related.
        /// </summary>
        public static string Jobprofesstions {
            get {
                return ResourceManager.GetString("Jobprofesstions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name (Not English).
        /// </summary>
        public static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name (English).
        /// </summary>
        public static string lastNameEN {
            get {
                return ResourceManager.GetString("lastNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length (cm).
        /// </summary>
        public static string length {
            get {
                return ResourceManager.GetString("length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked as answer.
        /// </summary>
        public static string markedAsAnswer {
            get {
                return ResourceManager.GetString("markedAsAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melli Code.
        /// </summary>
        public static string melliCode {
            get {
                return ResourceManager.GetString("melliCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string mobile {
            get {
                return ResourceManager.GetString("mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of firm you want to register....
        /// </summary>
        public static string namePlanReq {
            get {
                return ResourceManager.GetString("namePlanReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIOC Aproved Vendor List.
        /// </summary>
        public static string niocAVL {
            get {
                return ResourceManager.GetString("niocAVL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer is not useful.
        /// </summary>
        public static string notUseful {
            get {
                return ResourceManager.GetString("notUseful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer date.
        /// </summary>
        public static string offerDate {
            get {
                return ResourceManager.GetString("offerDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acception.
        /// </summary>
        public static string offerIsAccepted {
            get {
                return ResourceManager.GetString("offerIsAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack Count.
        /// </summary>
        public static string packCount {
            get {
                return ResourceManager.GetString("packCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string patentDescription {
            get {
                return ResourceManager.GetString("patentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (English).
        /// </summary>
        public static string patentDescriptionEN {
            get {
                return ResourceManager.GetString("patentDescriptionEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue date....
        /// </summary>
        public static string patentissueDate {
            get {
                return ResourceManager.GetString("patentissueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patent No..
        /// </summary>
        public static string patentNo {
            get {
                return ResourceManager.GetString("patentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office country.
        /// </summary>
        public static string patentOfficeCountry {
            get {
                return ResourceManager.GetString("patentOfficeCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patent status.
        /// </summary>
        public static string PatentStatus {
            get {
                return ResourceManager.GetString("PatentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter patent title (Not English).
        /// </summary>
        public static string patentTitle {
            get {
                return ResourceManager.GetString("patentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter patent title (English).
        /// </summary>
        public static string patentTitleEN {
            get {
                return ResourceManager.GetString("patentTitleEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL of patent....
        /// </summary>
        public static string patentURL {
            get {
                return ResourceManager.GetString("patentURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay acception date.
        /// </summary>
        public static string payAcceptDate {
            get {
                return ResourceManager.GetString("payAcceptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Amount.
        /// </summary>
        public static string payAmount {
            get {
                return ResourceManager.GetString("payAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string payBank {
            get {
                return ResourceManager.GetString("payBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Code.
        /// </summary>
        public static string payCode {
            get {
                return ResourceManager.GetString("payCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Date.
        /// </summary>
        public static string payDate {
            get {
                return ResourceManager.GetString("payDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Type.
        /// </summary>
        public static string payType {
            get {
                return ResourceManager.GetString("payType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string phoneNo {
            get {
                return ResourceManager.GetString("phoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLan.
        /// </summary>
        public static string plan {
            get {
                return ResourceManager.GetString("plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description about your company or store name.
        /// </summary>
        public static string planRequestCoStoreAbout {
            get {
                return ResourceManager.GetString("planRequestCoStoreAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your company or store name.
        /// </summary>
        public static string planRequestCoStoreName {
            get {
                return ResourceManager.GetString("planRequestCoStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Type.
        /// </summary>
        public static string planType {
            get {
                return ResourceManager.GetString("planType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production or trade....
        /// </summary>
        public static string PorT {
            get {
                return ResourceManager.GetString("PorT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string post {
            get {
                return ResourceManager.GetString("post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power (kw).
        /// </summary>
        public static string power {
            get {
                return ResourceManager.GetString("power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price in Rls.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production country.
        /// </summary>
        public static string productionCountry {
            get {
                return ResourceManager.GetString("productionCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name (Not English).
        /// </summary>
        public static string productName {
            get {
                return ResourceManager.GetString("productName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name (English).
        /// </summary>
        public static string productNameEN {
            get {
                return ResourceManager.GetString("productNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decription (Not English).
        /// </summary>
        public static string professionDescription {
            get {
                return ResourceManager.GetString("professionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decription (English).
        /// </summary>
        public static string professionDescriptionEN {
            get {
                return ResourceManager.GetString("professionDescriptionEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession (Not English).
        /// </summary>
        public static string professionName {
            get {
                return ResourceManager.GetString("professionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession (English).
        /// </summary>
        public static string professionNameEN {
            get {
                return ResourceManager.GetString("professionNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project description.
        /// </summary>
        public static string projectDescription {
            get {
                return ResourceManager.GetString("projectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project title.
        /// </summary>
        public static string projectName {
            get {
                return ResourceManager.GetString("projectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project value.
        /// </summary>
        public static string projectValue {
            get {
                return ResourceManager.GetString("projectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question body.
        /// </summary>
        public static string questionBody {
            get {
                return ResourceManager.GetString("questionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question subject.
        /// </summary>
        public static string questionSubject {
            get {
                return ResourceManager.GetString("questionSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration code.
        /// </summary>
        public static string regCode {
            get {
                return ResourceManager.GetString("regCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register date.
        /// </summary>
        public static string regDate {
            get {
                return ResourceManager.GetString("regDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date.
        /// </summary>
        public static string reqDate {
            get {
                return ResourceManager.GetString("reqDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School (Not English).
        /// </summary>
        public static string school {
            get {
                return ResourceManager.GetString("school", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School (English).
        /// </summary>
        public static string schoolEN {
            get {
                return ResourceManager.GetString("schoolEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time.
        /// </summary>
        public static string semDate {
            get {
                return ResourceManager.GetString("semDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string semDesc {
            get {
                return ResourceManager.GetString("semDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration(minute).
        /// </summary>
        public static string semDuraion {
            get {
                return ResourceManager.GetString("semDuraion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public webinar.
        /// </summary>
        public static string semIsPublic {
            get {
                return ResourceManager.GetString("semIsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max audiences.
        /// </summary>
        public static string semMaxAudience {
            get {
                return ResourceManager.GetString("semMaxAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string semPrice {
            get {
                return ResourceManager.GetString("semPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string semTitle {
            get {
                return ResourceManager.GetString("semTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service brand name (Not English).
        /// </summary>
        public static string servicebrandName {
            get {
                return ResourceManager.GetString("servicebrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service brand name (English).
        /// </summary>
        public static string servicebrandNameEN {
            get {
                return ResourceManager.GetString("servicebrandNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service provider company.
        /// </summary>
        public static string serviceCountry {
            get {
                return ResourceManager.GetString("serviceCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of Service (Months).
        /// </summary>
        public static string serviceEra {
            get {
                return ResourceManager.GetString("serviceEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name (Not English).
        /// </summary>
        public static string serviceName {
            get {
                return ResourceManager.GetString("serviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name (English).
        /// </summary>
        public static string serviceNameEN {
            get {
                return ResourceManager.GetString("serviceNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string sessionDesc {
            get {
                return ResourceManager.GetString("sessionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string sessionEndDate {
            get {
                return ResourceManager.GetString("sessionEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        public static string sessionOffer {
            get {
                return ResourceManager.GetString("sessionOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string sessionResult {
            get {
                return ResourceManager.GetString("sessionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string sessionStartDate {
            get {
                return ResourceManager.GetString("sessionStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session subject.
        /// </summary>
        public static string sessionSubject {
            get {
                return ResourceManager.GetString("sessionSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shabnam code.
        /// </summary>
        public static string shabnam {
            get {
                return ResourceManager.GetString("shabnam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share note.
        /// </summary>
        public static string shareNote {
            get {
                return ResourceManager.GetString("shareNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Free.
        /// </summary>
        public static string shipFree {
            get {
                return ResourceManager.GetString("shipFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State code.
        /// </summary>
        public static string stateCode {
            get {
                return ResourceManager.GetString("stateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State (Not English).
        /// </summary>
        public static string stateName {
            get {
                return ResourceManager.GetString("stateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State (English).
        /// </summary>
        public static string stateNameEN {
            get {
                return ResourceManager.GetString("stateNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store name (Not English).
        /// </summary>
        public static string storeName {
            get {
                return ResourceManager.GetString("storeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store name (English).
        /// </summary>
        public static string storeNameEN {
            get {
                return ResourceManager.GetString("storeNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string userName {
            get {
                return ResourceManager.GetString("userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (kg).
        /// </summary>
        public static string weight {
            get {
                return ResourceManager.GetString("weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width (cm).
        /// </summary>
        public static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        public static string word {
            get {
                return ResourceManager.GetString("word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word description.
        /// </summary>
        public static string wordDesc {
            get {
                return ResourceManager.GetString("wordDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English description related to this dictionary and word.
        /// </summary>
        public static string wordDescEn {
            get {
                return ResourceManager.GetString("wordDescEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not English description related to this dictionary and word.
        /// </summary>
        public static string wordDescFa {
            get {
                return ResourceManager.GetString("wordDescFa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English word.
        /// </summary>
        public static string wordEn {
            get {
                return ResourceManager.GetString("wordEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not English word.
        /// </summary>
        public static string wordFa {
            get {
                return ResourceManager.GetString("wordFa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wuarantee (Months).
        /// </summary>
        public static string wuarantee {
            get {
                return ResourceManager.GetString("wuarantee", resourceCulture);
            }
        }
    }
}
