//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Plan {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Plan() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Plan", typeof(Plan).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attend in events, exhibitions, ....
        /// </summary>
        public static string attendEvents {
            get {
                return ResourceManager.GetString("attendEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your firm will automatically, Be in sight of related people..
        /// </summary>
        public static string beInSight {
            get {
                return ResourceManager.GetString("beInSight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will classify your company according to the ISIC(International Standard Industrial Classification)..
        /// </summary>
        public static string classifyCompany {
            get {
                return ResourceManager.GetString("classifyCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will classify your store according to the ISIC(International Standard Industrial Classification)..
        /// </summary>
        public static string classifyStore {
            get {
                return ResourceManager.GetString("classifyStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Plan.
        /// </summary>
        public static string companyPlan {
            get {
                return ResourceManager.GetString("companyPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find another companies, stores, retailers and people..
        /// </summary>
        public static string findCompanies {
            get {
                return ResourceManager.GetString("findCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find another stores, companies, retailers and people..
        /// </summary>
        public static string findStores {
            get {
                return ResourceManager.GetString("findStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your products, services, Images, Files and ....
        /// </summary>
        public static string insertProduct {
            get {
                return ResourceManager.GetString("insertProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own your company profile..
        /// </summary>
        public static string OwnCompanyProfile {
            get {
                return ResourceManager.GetString("OwnCompanyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own your store profile..
        /// </summary>
        public static string OwnStoreProfile {
            get {
                return ResourceManager.GetString("OwnStoreProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  rls per year.
        /// </summary>
        public static string perYear {
            get {
                return ResourceManager.GetString("perYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post your news, have followers, connect with others and ....
        /// </summary>
        public static string postNews {
            get {
                return ResourceManager.GetString("postNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register for .
        /// </summary>
        public static string registerFor {
            get {
                return ResourceManager.GetString("registerFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced dynamic search, Brings your firm to people who are investigating in your activity field..
        /// </summary>
        public static string searchResult {
            get {
                return ResourceManager.GetString("searchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Plan.
        /// </summary>
        public static string storePlan {
            get {
                return ResourceManager.GetString("storePlan", resourceCulture);
            }
        }
    }
}
