//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TimeNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimeNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.TimeNames", typeof(TimeNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string daysAgo {
            get {
                return ResourceManager.GetString("daysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days later.
        /// </summary>
        public static string daysLater {
            get {
                return ResourceManager.GetString("daysLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string hoursAgo {
            get {
                return ResourceManager.GetString("hoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours later.
        /// </summary>
        public static string hoursLater {
            get {
                return ResourceManager.GetString("hoursLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        public static string justNow {
            get {
                return ResourceManager.GetString("justNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month.
        /// </summary>
        public static string lastMonth {
            get {
                return ResourceManager.GetString("lastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week.
        /// </summary>
        public static string lastWeek {
            get {
                return ResourceManager.GetString("lastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last year.
        /// </summary>
        public static string lastYear {
            get {
                return ResourceManager.GetString("lastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string minutesAgo {
            get {
                return ResourceManager.GetString("minutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes later.
        /// </summary>
        public static string minutesLater {
            get {
                return ResourceManager.GetString("minutesLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months ago.
        /// </summary>
        public static string monthsAgo {
            get {
                return ResourceManager.GetString("monthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months later.
        /// </summary>
        public static string monthsLater {
            get {
                return ResourceManager.GetString("monthsLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next month.
        /// </summary>
        public static string nextMonth {
            get {
                return ResourceManager.GetString("nextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next week.
        /// </summary>
        public static string nextWeek {
            get {
                return ResourceManager.GetString("nextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next year.
        /// </summary>
        public static string nextYear {
            get {
                return ResourceManager.GetString("nextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not yet.
        /// </summary>
        public static string notYet {
            get {
                return ResourceManager.GetString("notYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one hour ago.
        /// </summary>
        public static string oneHour {
            get {
                return ResourceManager.GetString("oneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one hour later.
        /// </summary>
        public static string oneHourLater {
            get {
                return ResourceManager.GetString("oneHourLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one minute ago.
        /// </summary>
        public static string oneMinute {
            get {
                return ResourceManager.GetString("oneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one minute later.
        /// </summary>
        public static string oneMinuteLater {
            get {
                return ResourceManager.GetString("oneMinuteLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to three weeks ago.
        /// </summary>
        public static string threeWeeksAgo {
            get {
                return ResourceManager.GetString("threeWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to three weeks later.
        /// </summary>
        public static string threeWeeksLater {
            get {
                return ResourceManager.GetString("threeWeeksLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string tomrrow {
            get {
                return ResourceManager.GetString("tomrrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two weeks ago.
        /// </summary>
        public static string twoWeeksAgo {
            get {
                return ResourceManager.GetString("twoWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two weeks later.
        /// </summary>
        public static string twoWeeksLater {
            get {
                return ResourceManager.GetString("twoWeeksLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years ago.
        /// </summary>
        public static string yearsAgo {
            get {
                return ResourceManager.GetString("yearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years later.
        /// </summary>
        public static string yearsLater {
            get {
                return ResourceManager.GetString("yearsLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string yesterday {
            get {
                return ResourceManager.GetString("yesterday", resourceCulture);
            }
        }
    }
}
